title: My Website
description: A GitHub Pages site with the Minima theme
baseurl: "" # Leave this empty for user sites; add "/repo-name" for project sites
url: "https://username.github.io" # Replace with your GitHub Pages URL
theme: minima
